import Articles from '../models/ArticleModel.js';

const SeederArticle = async () => {
	try {
		const articlesData = [
			{
				title: 'Manfaat Daur Ulang Sampah Plastik Bagi Lingkungan',
				text: 'Daur ulang sampah plastik menjadi langkah krusial dalam menjaga keberlanjutan lingkungan di era modern ini. Praktik daur ulang memainkan peran penting dalam mengurangi jumlah limbah plastik yang mencemari lingkungan dan mempengaruhi kehidupan satwa liar. Salah satu cara efektif dalam mendaur ulang plastik adalah dengan memisahkan sampah plastik dari sampah organik dan sampah lainnya di rumah tangga. Langkah ini memungkinkan plastik untuk diolah kembali menjadi bahan baku baru tanpa harus menghasilkan lebih banyak limbah.\n\nSelain mengurangi pencemaran lingkungan, mendaur ulang plastik juga berdampak positif terhadap ketersediaan sumber daya alam. Proses daur ulang membantu mengurangi kebutuhan akan bahan baku baru, seperti minyak bumi yang digunakan dalam produksi plastik. Dengan demikian, daur ulang membantu mengurangi tekanan terhadap ekosistem alam dan memperpanjang masa pakai sumber daya alam yang terbatas.\n\nAdopsi kebiasaan daur ulang juga memberikan manfaat sosial ekonomi yang signifikan. Ini menciptakan peluang baru untuk industri daur ulang, menciptakan lapangan kerja, dan meningkatkan kesadaran masyarakat akan pentingnya menjaga lingkungan. Ketika masyarakat mulai mempraktikkan daur ulang secara konsisten, mereka turut berkontribusi dalam upaya global untuk mengurangi jejak karbon dan menanggulangi masalah sampah plastik yang mengkhawatirkan.\n\nSecara keseluruhan, mendaur ulang sampah plastik bukan hanya sekadar tindakan individu, tetapi juga merupakan langkah strategis dalam membangun masyarakat yang lebih berkelanjutan secara lingkungan. Dengan meningkatkan edukasi dan akses terhadap fasilitas daur ulang yang efisien, kita dapat melangkah lebih jauh dalam mengatasi masalah pencemaran plastik dan meningkatkan kualitas hidup global untuk generasi mendatang.',
				image: 'manfaat-daur-ulang-sampah-plastik.jpeg',
				slug: 'manfaat-daur-ulang-sampah-plastik',
			},
			{
				title: 'Tips Mengurangi Penggunaan Plastik dalam Kehidupan Sehari-hari',
				text: 'Penggunaan plastik yang berlebihan memang menjadi masalah serius bagi lingkungan kita. Plastik sulit terurai dan sering kali berakhir sebagai sampah laut atau di tempat pembuangan akhir, menciptakan dampak negatif yang luas terhadap ekosistem laut dan kehidupan satwa liar. Untuk mengatasi masalah ini, ada beberapa langkah praktis yang dapat diambil setiap individu dalam kehidupan sehari-hari.\n\nSalah satu langkah pertama adalah mengganti kantong belanja plastik dengan yang reusable. Kantong belanja reusable terbuat dari bahan yang tahan lama dan dapat digunakan berkali-kali, mengurangi jumlah plastik sekali pakai yang kita hasilkan. Selain itu, menghindari penggunaan sedotan plastik dengan beralih ke sedotan stainless steel atau bambu juga dapat membantu mengurangi limbah plastik.\n\nDi dapur, penggunaan kemasan makanan yang ramah lingkungan juga dapat diterapkan. Misalnya, menggunakan wadah kaca atau stainless steel untuk menyimpan makanan daripada bungkus plastik sekali pakai. Beberapa toko makanan dan pasar juga mulai menawarkan opsi untuk membawa wadah sendiri untuk pengemasan makanan, mengurangi pemakaian wadah plastik sekali pakai.\n\nSelain itu, mendukung gerakan untuk mengurangi penggunaan plastik di restoran dan kedai kopi juga merupakan langkah yang positif. Memilih untuk membawa tempat minum sendiri atau menggunakan gelas kertas yang dapat didaur ulang dapat membantu mengurangi jumlah sampah plastik yang dihasilkan secara keseluruhan.\n\nDengan menerapkan langkah-langkah ini, setiap individu dapat memberikan kontribusi nyata dalam mengurangi dampak buruk penggunaan plastik terhadap lingkungan. Hal-hal kecil seperti ini, jika dilakukan secara konsisten oleh banyak orang, dapat memiliki dampak besar dalam melindungi bumi kita dari pencemaran plastik yang semakin meningkat.',
				image: 'tips-mengurangi-penggunaan-plastik.jpg',
				slug: 'tips-mengurangi-penggunaan-plastik',
			},
			{
				title: 'Tutorial Membuat Komposter Sederhana di Rumah',
				text: 'Komposter adalah salah satu solusi terbaik untuk mengurangi sampah organik di rumah sambil menghasilkan pupuk yang berguna bagi tanaman. Dengan membuat komposter sendiri di rumah, Anda dapat memanfaatkan sisa-sisa dapur seperti sisa sayuran, buah-buahan, daun kering, dan bahkan kertas sebagai bahan baku. Langkah pertama dalam membuat komposter adalah memilih wadah yang sesuai, bisa berupa tong atau kotak dengan ventilasi yang cukup untuk sirkulasi udara. Pastikan wadah tersebut mudah diakses untuk memudahkan proses pengadukan dan pembersihan.\n\nSetelah memiliki wadah, langkah berikutnya adalah menambahkan bahan-bahan organik ke dalam komposter secara bertahap. Campuran yang baik terdiri dari bahan hijau (seperti sisa makanan segar) dan bahan coklat (seperti daun kering atau potongan kertas). Perbandingan idealnya adalah dua bagian bahan hijau untuk satu bagian bahan coklat, namun ini bisa disesuaikan sesuai dengan bahan yang Anda miliki. Pastikan untuk tidak menambahkan daging, produk susu, atau minyak ke dalam komposter karena dapat menyebabkan bau tidak sedap atau menarik hama.\n\nProses berikutnya adalah mengaduk campuran secara teratur untuk memastikan bahwa bahan-bahan terurai dengan baik dan udara dapat mengalir secara optimal. Pengadukan juga membantu mempercepat proses dekomposisi sampah organik menjadi pupuk matang. Komposter sebaiknya diletakkan di tempat yang teduh namun terjangkau oleh hujan ringan, serta mudah diakses untuk mempermudah penambahan bahan dan pengambilan pupuk yang sudah jadi.\n\nDengan mengikuti langkah-langkah sederhana ini, Anda dapat membuat komposter sendiri di rumah dengan biaya terjangkau. Selain membantu mengurangi jumlah sampah yang dikirim ke tempat pembuangan akhir, Anda juga akan mendapatkan pupuk organik berkualitas tinggi yang dapat meningkatkan kesuburan tanah dan kesehatan tanaman di kebun Anda. Komposter buatan sendiri tidak hanya ramah lingkungan, tetapi juga memberikan manfaat jangka panjang bagi lingkungan sekitar dan tanaman yang Anda tanam.',
				image: 'tutorial-membuat-komposter-sederhana.jpg',
				slug: 'tutorial-membuat-komposter-sederhana',
			},
			{
				title: 'Keuntungan Ekonomi dari Daur Ulang Sampah Kertas',
				text: 'Daur ulang kertas memiliki peran yang krusial dalam menjaga keberlanjutan lingkungan. Proses ini dimulai dari pengumpulan limbah kertas bekas, yang kemudian dipilah, dibersihkan, dan diolah menjadi bahan baku baru. Langkah pertama adalah pengumpulan dan pemilahan kertas bekas dari berbagai sumber seperti perkantoran, sekolah, dan rumah tangga. Setelah itu, kertas diproses untuk menghilangkan tinta dan kotoran dengan proses pencucian dan penggilingan. Selanjutnya, serat kertas ini dimurnikan dan direproduksi menjadi lembaran kertas baru yang siap digunakan kembali.\n\nManfaat dari daur ulang kertas tidak hanya terbatas pada perlindungan lingkungan, tetapi juga mencakup aspek ekonomi yang signifikan. Industri daur ulang kertas menciptakan peluang bisnis baru dalam rantai pasokan yang berkelanjutan. Proses ini melibatkan penggunaan teknologi canggih untuk meningkatkan efisiensi dan kualitas produk akhir. Selain itu, industri ini juga menciptakan lapangan kerja dalam berbagai tingkatan, dari pengumpulan sampai dengan pengolahan akhir kertas daur ulang.\n\nDalam konteks ekonomi global saat ini, daur ulang kertas dapat menjadi strategi yang berharga untuk mengurangi ketergantungan pada sumber daya alam yang terbatas. Dengan mengurangi permintaan akan bahan baku baru, daur ulang kertas membantu dalam meminimalkan dampak deforestasi dan degradasi lingkungan. Secara keseluruhan, praktik daur ulang kertas tidak hanya mendukung kelestarian alam, tetapi juga mempromosikan pertumbuhan ekonomi yang berkelanjutan melalui penggunaan kembali sumber daya yang ada.\n\nOleh karena itu, mengadopsi praktik daur ulang kertas bukan hanya berarti berkontribusi pada pelestarian lingkungan, tetapi juga membuka peluang baru dalam sektor ekonomi yang ramah lingkungan. Dengan meningkatnya kesadaran akan pentingnya pengelolaan limbah dan kebutuhan akan solusi berkelanjutan, daur ulang kertas menjadi langkah strategis yang tidak hanya relevan tetapi juga mendukung pertumbuhan ekonomi yang inklusif dan berkelanjutan.',
				image: 'keuntungan-ekonomi-dari-daur-ulang-sampah-kertas.jpg',
				slug: 'keuntungan-ekonomi-dari-daur-ulang-sampah-kertas',
			},
			{
				title: '5 Tips Hemat Energi Saat Mendaur Ulang Logam',
				text: 'Mendaur ulang logam adalah langkah penting dalam upaya kita untuk mengurangi dampak lingkungan. Proses daur ulang logam membutuhkan jauh lebih sedikit energi dibandingkan dengan ekstraksi logam dari bijih tambang baru. Ini berarti bahwa dengan mendaur ulang logam, kita dapat secara signifikan mengurangi emisi karbon yang dihasilkan dari proses penambangan dan pemrosesan logam baru. Di rumah atau tempat kerja, ada beberapa tips praktis yang dapat kita terapkan untuk mengoptimalkan proses daur ulang logam.\n\nPertama, pastikan untuk memilah logam berdasarkan jenisnya sebelum didaur ulang. Memilah logam-logam seperti aluminium, besi, tembaga, dan baja akan mempermudah proses daur ulang dan mengurangi waktu yang dibutuhkan untuk pemrosesan selanjutnya. Kedua, bersihkan logam dari kontaminan sebelum mendaur ulang. Contohnya, botol kaleng atau kaleng makanan harus dibersihkan dari sisa-sisa makanan atau minuman agar tidak mencemari proses daur ulang dan mengurangi efisiensi.\n\nSelanjutnya, manfaatkan pelayanan daur ulang yang tersedia di komunitas Anda. Banyak daerah sekarang memiliki fasilitas daur ulang yang mengumpulkan logam dari rumah-rumah atau kantor-kantor. Dengan menggunakan layanan ini, Anda dapat memastikan bahwa logam yang didaur ulang akan diproses dengan benar dan efisien. Terakhir, edukasikan diri sendiri dan orang lain di sekitar Anda tentang pentingnya daur ulang logam. Semakin banyak orang yang terlibat dalam praktek daur ulang ini, semakin besar dampak positifnya terhadap lingkungan kita.\n\nSecara keseluruhan, mendaur ulang logam bukan hanya tentang mengurangi limbah, tetapi juga tentang mengurangi jejak karbon kita. Dengan menerapkan langkah-langkah praktis ini di rumah atau tempat kerja, kita dapat berkontribusi pada upaya global untuk meminimalkan konsumsi energi dan mengurangi emisi gas rumah kaca yang merugikan lingkungan.',
				image: 'tips-hemat-energi-saat-mendaur-ulang-logam.jpg',
				slug: 'tips-hemat-energi-saat-mendaur-ulang-logam',
			},
			{
				title: 'Cara Mengolah Sampah Organik Menjadi Pupuk Berkualitas Tinggi',
				text: 'Mengolah sampah organik menjadi pupuk merupakan langkah krusial dalam mengurangi dampak negatif sampah terhadap lingkungan. Dengan mengadopsi metode ini, kita dapat mengurangi volume sampah yang berakhir di tempat pembuangan akhir, serta menghasilkan bahan yang berguna bagi kebun atau tanaman. Salah satu metode yang efektif adalah komposing. Kompos adalah hasil dekomposisi bahan organik oleh mikroorganisme, seperti bakteri dan jamur, menjadi bahan yang kaya nutrisi untuk tanaman. Proses ini dapat dilakukan dengan mengumpulkan sisa makanan organik, daun kering, atau serasah dan mengatur lapisan yang sesuai untuk mempromosikan dekomposisi yang sehat.\n\nSelain itu, metode lain yang populer adalah pengomposan cepat menggunakan alat pengompos komersial atau pembuat kompos. Alat-alat ini dirancang untuk mempercepat proses dekomposisi dengan mengatur suhu dan kelembaban yang optimal serta memperlancar sirkulasi udara. Pendekatan ini sangat cocok untuk rumah tangga atau skala kecil yang ingin menghasilkan pupuk dengan cepat dan efisien.\n\nSelanjutnya, untuk yang memiliki lahan terbatas, metode pengomposan dalam wadah atau kontainer juga dapat diterapkan. Ini melibatkan penggunaan wadah tertutup yang memungkinkan pengontrolan yang lebih baik terhadap kondisi lingkungan dekomposisi. Dengan cara ini, bahkan di lingkungan perkotaan atau apartemen, kita dapat mengelola sampah organik menjadi pupuk tanaman dengan efektif.\n\nTerakhir, penting untuk edukasi dan kesadaran masyarakat dalam mengadopsi praktik mengolah sampah organik menjadi pupuk. Dengan memberikan informasi tentang manfaat lingkungan dari pengomposan, masyarakat dapat lebih termotivasi untuk berpartisipasi aktif dalam upaya pengelolaan sampah secara berkelanjutan. Dengan demikian, pengolahan sampah organik menjadi pupuk bukan hanya mengurangi beban sampah, tetapi juga berkontribusi pada keberlanjutan lingkungan secara keseluruhan.',
				image: 'cara-mengolah-sampah-organik-menjadi-pupuk-berkualitas.png',
				slug: 'cara-mengolah-sampah-organik-menjadi-pupuk-berkualitas',
			},
			{
				title: 'Inovasi Dalam Pengelolaan Limbah Plastik: Teknologi Terkini',
				text: 'Teknologi terkini memang memainkan peran yang sangat penting dalam menangani masalah limbah plastik global. Di seluruh dunia, inovasi terbaru dalam pengelolaan limbah plastik menjadi sorotan utama dalam upaya untuk mengurangi dampak negatifnya terhadap lingkungan dan kesehatan manusia. Salah satu perkembangan signifikan adalah teknologi daur ulang canggih yang semakin mutakhir. Proses daur ulang ini tidak hanya lebih efisien dalam memisahkan berbagai jenis plastik, tetapi juga mampu menghasilkan produk yang memiliki kualitas serupa dengan produk baru. Dengan demikian, teknologi ini tidak hanya mengurangi jumlah limbah yang berakhir di tempat pembuangan akhir, tetapi juga mendukung pemanfaatan kembali sumber daya yang berharga.\n\nSelain itu, penggunaan bahan pengganti plastik juga menjadi fokus utama dalam upaya mengurangi konsumsi plastik sekali pakai. Bahan-bahan ini sering kali ramah lingkungan dan dapat terurai dengan lebih cepat daripada plastik tradisional. Inovasi dalam pengembangan bahan-bahan ini tidak hanya melibatkan penelitian untuk menciptakan material baru yang lebih berkelanjutan, tetapi juga mempromosikan penggunaan bahan alami sebagai alternatif yang lebih ramah lingkungan.\n\nTeknologi sensor dan pemantauan juga telah memainkan peran kunci dalam manajemen limbah plastik. Dengan adopsi sensor canggih dan sistem pemantauan, pengelola limbah dapat melacak dan mengelola aliran limbah plastik dengan lebih efisien. Hal ini membantu dalam menanggulangi masalah seperti pencemaran lingkungan akibat pembuangan limbah yang tidak terkendali.\n\nTerakhir, pendekatan yang terintegrasi antara teknologi, kebijakan publik, dan kesadaran masyarakat menjadi kunci keberhasilan dalam menghadapi masalah limbah plastik. Dengan terus mengembangkan dan menerapkan inovasi-inovasi ini secara global, diharapkan dapat tercipta lingkungan yang lebih bersih dan berkelanjutan untuk generasi mendatang.',
				image: 'inovasi-dalam-pengelolaan-limbah-plastik.jpeg',
				slug: 'inovasi-dalam-pengelolaan-limbah-plastik',
			},
			{
				title: 'Manfaat Menggunakan Produk Ramah Lingkungan dalam Kehidupan Sehari-hari',
				text: 'Produk ramah lingkungan menawarkan solusi yang penting dalam mengurangi dampak negatif terhadap lingkungan dan kesehatan manusia. Menggunakan produk seperti bahan bangunan ramah lingkungan, seperti daur ulang atau bahan alami, dapat mengurangi jejak karbon dan limbah toksik. Misalnya, mengganti bahan kimia berbahaya dengan alternatif yang ramah lingkungan dapat mengurangi polusi udara dan air yang berdampak langsung pada kesehatan manusia. Selain itu, produk-produk ini sering kali lebih tahan lama dan memerlukan perawatan lebih sedikit, mengurangi penggunaan sumber daya secara keseluruhan.\n\nDampak jangka panjang dari penggunaan produk ramah lingkungan sangat signifikan. Langkah-langkah seperti memilih produk dengan label sertifikasi lingkungan dapat membantu mendukung praktik pertanian dan industri yang berkelanjutan. Hal ini tidak hanya menjaga kualitas air dan tanah, tetapi juga mendukung keanekaragaman hayati dan ekosistem yang penting bagi keseimbangan lingkungan global. Investasi jangka panjang dalam produk yang berkelanjutan juga dapat menginspirasi perubahan dalam industri secara keseluruhan, mendorong inovasi teknologi yang lebih ramah lingkungan.\n\nBagi konsumen, penting untuk memilih produk berkelanjutan dengan mempertimbangkan sumber daya yang digunakan dalam proses produksinya, serta dampak keseluruhan produk terhadap lingkungan. Memilih produk yang terbuat dari bahan daur ulang atau yang dapat didaur ulang kembali setelah pemakaian adalah salah satu cara untuk mengurangi limbah dan mendorong ekonomi sirkular. Selain itu, mendukung perusahaan yang berkomitmen pada praktik-produksi yang bertanggung jawab dapat memberikan dorongan bagi produsen lain untuk mengikuti jejak yang sama.\n\nSecara keseluruhan, pergeseran menuju produk ramah lingkungan bukan hanya tentang menjaga lingkungan hidup untuk generasi mendatang, tetapi juga tentang menjaga kesehatan kita hari ini. Dengan memilih produk yang berkelanjutan, kita tidak hanya memberdayakan diri kita sendiri untuk hidup lebih sehat, tetapi juga berkontribusi pada perlindungan lingkungan yang semakin penting dalam menghadapi tantangan global saat ini.',
				image: 'manfaat-menggunakan-produk-ramah-lingkungan.webp',
				slug: 'manfaat-menggunakan-produk-ramah-lingkungan',
			},
			{
				title: 'Langkah-langkah Praktis untuk Mengurangi Limbah Elektronik',
				text: 'Di era digital ini, limbah elektronik semakin menjadi masalah global yang mendesak. Perangkat elektronik seperti smartphone, laptop, dan perangkat keras lainnya cepat menjadi usang atau tidak terpakai, meninggalkan jejak limbah yang besar. Langkah-langkah praktis untuk mengatasi masalah ini sangat penting. Salah satu cara yang efektif adalah dengan mendaur ulang perangkat elektronik yang tidak terpakai. Dengan mendaur ulang, komponen-komponen berharga dari perangkat tersebut dapat dipulihkan dan digunakan kembali dalam produk baru, mengurangi tekanan pada sumber daya alam untuk memproduksi komponen baru.\n\nSelain mendaur ulang, mendonasikan perangkat yang masih berfungsi adalah opsi lain yang dapat mengurangi limbah elektronik. Banyak organisasi nirlaba atau program pemerintah menerima donasi perangkat elektronik untuk didistribusikan kembali kepada mereka yang membutuhkan, baik di dalam maupun di luar negeri. Hal ini tidak hanya membantu mengurangi limbah, tetapi juga memberikan manfaat langsung kepada mereka yang mungkin tidak mampu membeli perangkat baru.\n\nPentingnya mendidik masyarakat tentang pentingnya pengelolaan limbah elektronik juga tidak boleh diabaikan. Kampanye pendidikan yang efektif dapat meningkatkan kesadaran akan dampak negatif limbah elektronik dan mendorong individu untuk mengambil langkah-langkah konkrit dalam mengelola perangkat elektronik mereka dengan lebih bijaksana. Ini termasuk mengambil keputusan yang lebih berkelanjutan dalam pembelian perangkat baru dan mempertimbangkan opsi perbaikan daripada penggantian.\n\nTerakhir, pemerintah dan produsen perangkat elektronik perlu bekerja sama untuk menciptakan kebijakan yang mendukung daur ulang dan pengelolaan limbah elektronik yang bertanggung jawab. Kebijakan yang ketat dan insentif untuk praktik ramah lingkungan dapat mendorong industri teknologi untuk menghasilkan produk yang lebih tahan lama dan mudah didaur ulang. Dengan langkah-langkah ini, kita dapat bersama-sama mengurangi dampak limbah elektronik terhadap lingkungan dan sumber daya alam global.',
				image: 'langkah-praktis-untuk-mengurangi-limbah-elektronik.png',
				slug: 'langkah-praktis-untuk-mengurangi-limbah-elektronik',
			},
			{
				title: 'Pengelolaan Sampah Plastik: Tantangan dan Solusi',
				text: 'Sampah plastik telah menjadi salah satu tantangan utama dalam pengelolaan limbah di seluruh dunia. Kehadirannya yang merajalela tidak hanya mencemari lingkungan tetapi juga mengancam keberlanjutan ekosistem global. Negara-negara di seluruh dunia menghadapi kesulitan dalam mengelola jumlah yang semakin meningkat dari sampah plastik ini. Berbagai solusi tradisional seperti daur ulang dan pengurangan penggunaan plastik sekali pakai telah diterapkan, namun tantangan tersebut terus berkembang seiring dengan pertumbuhan konsumsi plastik global.\n\nSalah satu solusi inovatif yang sedang dikembangkan adalah teknologi daur ulang tingkat lanjut, yang dapat mengubah sampah plastik menjadi bahan baku yang bernilai ekonomis. Teknologi seperti pyrolysis dan depolimerisasi memungkinkan konversi plastik bekas menjadi bahan bakar atau bahan kimia yang dapat digunakan kembali. Selain itu, pendekatan baru dalam desain produk juga menjadi fokus, dengan mengembangkan plastik yang lebih mudah didaur ulang atau mengganti plastik dengan bahan yang lebih ramah lingkungan.\n\nNamun, tantangan utama tetap berada pada skala operasional dan kebijakan yang memadai. Banyak negara masih menghadapi kendala dalam infrastruktur daur ulang yang memadai dan kurangnya insentif bagi industri untuk mengadopsi teknologi yang lebih berkelanjutan. Untuk mengatasi masalah ini, diperlukan kerjasama internasional yang lebih kuat dalam hal regulasi dan investasi dalam infrastruktur pengelolaan limbah.\n\nSecara keseluruhan, mengelola sampah plastik membutuhkan pendekatan holistik yang melibatkan inovasi teknologi, perubahan perilaku konsumen, serta dukungan kuat dari pemerintah dan sektor industri. Hanya dengan upaya bersama, kita dapat mengurangi dampak negatif dari sampah plastik terhadap lingkungan dan membangun masa depan yang lebih berkelanjutan bagi generasi mendatang.',
				image: 'pengelolaan-sampah-plastik-tantangan-dan-solusi.jpg',
				slug: 'pengelolaan-sampah-plastik-tantangan-dan-solusi',
			},
		];

		for (const article of articlesData) {
			const existingArticle = await Articles.findOne({
				where: { slug: article.slug },
			});
			if (existingArticle) {
				console.log(
					`Article with slug "${article.slug}" already exists. Skipping seeding.`
				);
			} else {
				await Articles.create(article);
				console.log(`Article "${article.title}" seeded successfully!`);
			}
		}
	} catch (error) {
		console.error('Failed to seed articles:', error);
	}
};

export default SeederArticle;
